/**
 * Booklet 1, Chapter 12: The Resurrection of the Dead
 * Author: Franck
 *
 * See EXAMPLE-CHAPTER.js for all available content block types.
 */
BOOKLET_CONTENT["1-12"] = {
  content: [
    { type: "quote", text: "Let not your heart be troubled. You believe in Elohim (God), believe also in me. In my Father\u2019s house are many dwelling places. If not, I would have told you. I go to prepare you a place. And when I have gone and prepared to you a place, I come again, and I will take you to myself, so that where I am, you may be also.", source: "John 14:1-3" },
    "In this passage, the verb \u201Cto take\u201D clearly means \u201Cto snatch out.\u201D Many people ridicule the Lord\u2019s promise to the Church concerning His return. Yet, He clearly said that he will come back for us.",
    "This is also essentially one of the (if not the most) crucial promises made by the Lord Yehoshua Mashiah (Jesus Christ) to His children; the promise of one day fetching and taking us to a place that He Himself has prepared for us. How do you not long for that to happen? Doesn\u2019t your soul yearn for the accomplishment of such a promise? We are living in a world where wickedness keeps on increasing to the point of affecting the foundation of society, that is the family. In a society where one witnesses daily how \u201Cwrong\u201D is being called \u201Cright\u201D, and vice-versa, the love of many has frozen, leaving behind nothing but a block of insensible people, not having the love of their neighbors at heart. Turn on the radio and all you hear are cases of murders of children or women by the ones who are supposed to protect them: their fathers or husbands.",
    "Turn on the television and all you see is similar news, wars, laws voted by various governments around the world that make one wonder what are the true intentions of having such laws in place. And yet in the midst of this, our hope as the Church of Mashiah (Christ) is found on the promise of our Lord to one day come and fetch us. This constitutes our true hope and gives us the strength to forgive those who hurt us, to humble ourselves and accept our weaknesses, to love everyone regardless of the color of their skin and to not let ourselves be attracted by the lust of this world.",
    { type: "heading", text: "The Snatching out of the Church (The Rapture of the Church)" },
    "In the first book of Thessalonians in chapter 4 and verse 17, the apostle Paulos (Paul) says: \u201CThen we, the living who remain, will be caught up together with them in the clouds to meet the Lord in the air, and so we will always be with the Lord.\u201D",
    "The words \u201Ccaught up\u201D in the above verse come from the Greek word \u201Charpazo\u201D which means \u201Cto seize\u201D or \u201Cto snatch out\u201D. These words are used today by many evangelical churches in its Latin form \u201Crapio\u201D, translated to rapture in English. The apostle Paulos (Paul) wrote these words to the church of Thessalonica so that they may not be ignorant of the Hope they have in the Lord and not mourn about those who have fallen asleep (died) like people who do not have any hope. The apostle Paulos (Paul) explains that when this day comes, at the sound of the last trumpet, Elohim will snatch His church. This is further explained in the letter written by the apostle Paulos (Paul) to the church of the Corinthians: \u201CBehold, I tell you a mystery: We indeed will not all fall asleep, but we will all be changed, in an atom of time, in the twinkling of an eye, at the last trumpet. For the trumpet will sound, and the dead will be risen incorruptible, and we will be changed. For this corruptible must put on incorruption, and this mortal put on immortality. So when this corruptible will have put on incorruption, and this mortal will have put on immortality, then will be brought to pass the word that is written: Death was swallowed up in victory\u201D (1 Corinthians 15:51-54).",
    "The resurrection of our flesh into an incorruptible body is our hope as the Church of Mashiah. This combined with a new earth and a new heaven where eternal peace and joy in the unhindered presence of our redeemer and Elohim, Yehoshua Mashiah, is the ultimate future of the Church of Mashiah. As the church of Mashiah, it is good for us to know what Elohim has planned for the future. It is even more important for us since the Lord has ensured that such events are written in the scriptures for our instruction. We will therefore look at some biblical prophecies concerning the end of times throughout this session.",
    { type: "heading", text: "The Snatching-out of the Church, the day of our Lord Yehoshua Mashiah" },
    "In the scripture, the unknown day during which the Church of Mashiah will be snatched out is referred to as the \u201Cday of our Lord Yehoshua Mashiah\u201D. \u201CI thank my Elohim always on your behalf, for the grace of Elohim which having been given you in Mashiah Yehoshua, that in everything you are enriched in him in all word and all knowledge, as the testimony of Mashiah was confirmed in you. So that you come behind in no gift of grace, waiting assiduously and patiently for the revelation of our Lord Yehoshua Mashiah, who will also confirm you till the end to be irreproachable in the day of our Lord Yehoshua Mashiah\u201D (1 Corinthians chapter 1, verses 4 to 8).",
    "Do you, child of Elohim, realize that you are so precious to the Lord Yehoshua (Jesus) that the day of your resurrection is being so awaited by the Lord Yehoshua to the point where He calls it His own day? This is the day you will finally be united with your Lord; the bride will unite with her spouse and will celebrate their love. This is the day of \u201Cthe marriage of the lamb.\u201D As a bride, are you, church of Mashiah, longing for that day? Your spouse is. He will descend, shake the principalities living in the second heaven to receive you and you shall dwell in the presence of the Lord forever. Dear reader, will you be part of such a glorious scene? Will you be amongst those whom the Lord will find ready? For that day is not reserved for all.",
    { type: "heading", text: "A day reserved for the Spotless and Unwrinkled bride" },
    "Does the snatching of the church concern every self-proclaimed \u201CChristian\u201D? The answer is found in various biblical verses. John 1:12-13 \u201CBut as many as received him, to those who believe in his name, he gave them the power to become children of Elohim, who were born not of blood, nor of the will of the flesh, nor of the will of man, but out of Elohim\u201D and John 3:1-6 \u201CBut there was a man out of the Pharisees, Nikodemos his name, one of the rulers of the Jews. This one came by night to Yehoshua and said to him: Rabbi, we know that you are a Teacher come from Elohim, for no one can do the signs that you do, unless Elohim be with him. Yehoshua answered and said to him: Amen, amen, I say to you: Unless someone is born from above, he cannot see the Kingdom of Elohim. Nikodemos says to him: How can a human being be born when he is old? Can he a second time enter in his mother\u2019s womb and be born? Yehoshua answered: Amen, amen, I say to you: Unless a man be born out of water and of Spirit, he cannot enter into the kingdom of Elohim. That which is born out of the flesh is flesh, and that which is born out of the Spirit is spirit.\u201D",
    "From the above verses, only those who are born of water and Spirit can enter the kingdom of Elohim. Only those, who have been regenerated by the Word of Elohim and sealed with the Holy Spirit, the Spirit of Mashiah can enter the kingdom of Elohim. For whoever is not marked or does not have the Spirit of the spouse (Yehoshua Mashiah) does not belong to Him (Romans chapter 8, verse 9). Only those who have been regenerated by the spirit of Mashiah, who persevere till the end and let their heart be transformed into a pure heart, loving Elohim and denying oneself, persevering in such walk shall be snatched out by the Lord. For many are called but few are chosen (Matthew chapter 22, verse 14); And only those who endures to the end shall be (Matthew 24, 13).",
    "Dear reader, do you believe in Mashiah? If you do not, I invite you to seek for the True Elohim while there is still time. Seek for the face of Him who created you and let Him reveal Himself to you for the salvation of your soul and your deliverance from the wrath which is soon to come and be poured on the nations.",
    "To you that have once seen the Hand of Elohim and know that He has been knocking at the door of your heart, but you have always let many distractions keep you away from His meek voice, it is time to hear the voice of the Lord. Repent from your ways, come and take refuge in Him. To you who have known the Lord, who have been transformed and one day decided to stop walking in the Lord, whatever reason, I encourage you to come back to Your Father. Confess your sins and wholeheartedly come back to the One and Only, you know to be the True Solution that you need. Do not let the door of the ark close, for now is the right time to wake up from sleeping. As Christians forming the body of Mashiah in Spirit will be snatched from this evil world. The Bible teaches us that their body will be changed into something glorious.",
    { type: "heading", text: "The Transformation of the Body" },
    { type: "quote", text: "For this we say to you by the word of the Lord, that we, the living who remain to the parousia of the Lord, will not precede those asleep. Because the Lord himself, with a shout of command, with the voice of an archangel, and with the trumpet of Elohim, will descend from heaven and the dead in Mashiah will rise first. Then we, the living who remain, will be caught up together with them in the clouds to meet the Lord in the air, and so we will always be with the Lord.", source: "1 Thessalonians 4:15-17" },
    "In the above verse, it is clearly shown that two things will happen. The saints of the Church who had died will resurrect from the dead first and the saints who will still be alive on earth will have their body transformed and they will both be caught up in the clouds. We will be given a new body, like the body of our Lord Yehoshua Mashiah when He rose from the dead.",
    "A glorious body, free of any disease, any weakness and the weight of age. Following our bodies being transformed, we will proceed to the tribunal or the judgement seat of Mashiah. \u201CFor our commonwealth of citizens is in the heavens, from which also we assiduously and patiently wait for the Savior, the Lord Yehoshua Mashiah, who will transform our body of humiliation that it may be conformed to his glorious body according to the efficiency whereby he is able even to subject all things to himself\u201D Philippians chapter 3:20-21.",
  ],
  supportingVerses: [],
  closing: ""
};
