/**
 * Booklet 1, Chapter 8: The Work of the Cross
 * Author: Franck
 *
 * See EXAMPLE-CHAPTER.js for all available content block types.
 */
BOOKLET_CONTENT["1-8"] = {
  content: [
    "In this present century, the word of the cross is more than ever a folly, both for some Christians and for non-believers in Yehoshua (Jesus) Ha Mashiah (Christ). For several years now, another gospel has been proclaimed in many so-called Christian assemblies and on social media. This gospel is completely devoid of the word of the cross, for it exalts humankind and encourages it to enrich itself with earthly goods. It glorifies the world, material possessions, personal development, and the frenzied pursuit of inner peace. Humanity has thus become the center of the majority of Christian assemblies, thereby taking the place of the Creator. Paulos (Paul) said of this type of person that he prefers to worship and serve the creature instead of the Creator, who is eternally blessed.",

    "All this proves that the word of the cross is no longer preached as it was in the first century. Yet, the cross is the central message of the Bible. Mixing this word with false doctrines produces Christians who misunderstand their Elohim (God) and inevitably leads them to syncretism, that is, \u201ca system that tends to merge several different doctrines\u201d. It is therefore a mixture of various influences. In the religious sphere, it is the fusion of different cults or doctrines. The principle is to blend two or more religions to make one.",

    { type: "heading", text: "What is the cross?" },

    "This question is very important because, unfortunately, thousands of Christians don\u2019t even know what the cross truly is. For many people, the cross is just a fetish, a small crucifix worn around the neck for protection against demons, misfortune, accidents, etc. Others know more about their pastors than the Word of the cross. We often meet Christians who talk more about their church building or their pastor than about the death and resurrection of Yehoshua.",

    { type: "quote", text: "Then they spat in his face and punched him. And others struck him with rods, saying: Mashiah, prophesy to us who is the one who struck you.", source: "Mattithyah 26:67-68" },

    { type: "quote", text: "Then he released Barabbas for them, but Yehoshua, having scourged him, he handed him over to be crucified.", source: "Mattithyah 27:26" },

    "Before being crucified, the Lord endured a great deal of physical and moral abuse. The Jews and Romans spat on him, hurled insults and blasphemies at him, beat him with sticks, and flogged him. Indeed, among the Romans, flogging was the punishment preceding crucifixion. The instrument used for flogging was a whip with several cords, each ending in a hook that tore the skin with each blow. Judging by the spectacle the soldiers staged to punish Yehoshua, it is clear that they struck him with great pleasure and bitter zeal, without any restraint or moderation. For, unlike the Jews, who were limited to forty lashes so that the punishment would not lead to death, the Romans had no such restrictions. In some cases, this punishment, intended as a prelude to crucifixion, could lead to death. While they were mistreating him, they wove a crown of thorns for him and pressed it onto his head.",

    "The shedding of the blood of Yehoshua ha Mashiah produced a great number of consequences. Indeed, the Lord overcame all the powers that separated Him from humanity. He conquered sin: \u201cFor what was impossible for the Torah (the Law), in that it was weak because of the flesh, Elohim having sent his own Son in flesh to the likeness of sin, and about sin, condemned sin in the flesh\u201d (Romans 8:3). He defeated Satan and the demons: \u201cHaving stripped the principalities and authorities, he made a show of them publicly, triumphing over of them in it\u201d (Colossians 2:15) and \u201c\u2026through death he might render powerless him who had the sovereign might of death, that is, the devil\u201d (Hebrews 2:14). He has overcome the world: \u201cI have spoken to you these things, so that in me you might have peace. In the world you have tribulation. But be of good courage! I, have overcome the world\u201d (Yohanan 16:33). Furthermore, he erased the act (the Mosaic carnal ordinances) that condemned us: \u201cHe erased the handwriting of decrees that were against us, which was opposed to us, and he has taken it out of the midst nailing it to the cross\u201d (Colossians 2:14). And Yehoshua allowed the nations to approach Him, uniting them in the Spirit to the assembly of the Hebrews who believe in His name. Therefore, we are one body, one family, one nation. Through the sacrifice of Yehoshua, we have been redeemed from the empty way of life passed down by our ancestors (1 Petros 1:18-19). And our conscience has been cleansed from dead works, to serve the living Elohim (Hebrews 9:14). Thus, we have been cleansed from all sin (1 Yohanan 1:7), for we have been washed in the blood of Yehoshua (Revelation 1:5).",

    "Having been sanctified (Hebrews 13:12); we have peace with Elohim (Colossians 1:20). Thus, thanks to Yehoshua, we have been drawn closer to the Father (Ephesians 2:13). We have the freedom to enter the holy places (Hebrews 10:19-20); for we have been marked with the Holy Spirit (Ephesians 1:13); and our body has become a dwelling place of Elohim in the Spirit (Ephesians 2:21-22), for we have become His children (Yohanan 1:12-13).",

    "Having been justified (Romans 5:9) and acquired by the Lord (Acts 20:28), we have eternal life (Romans 6:23), and we have dominion over the power of darkness, for we have overcome Satan (Revelation 12:11).",

    "Reconciliation is the free act by which Elohim, by virtue of the blood of the Mashiah, who by his death made propitiation for our sins, reinstates the repentant sinner into the heavenly family (2 Corinthians 5:18-19). Through the atoning death of the Lord Yehoshua, the Christian becomes pleasing to Elohim. With the covenant with the Heavenly Father renewed, the communion between the Christian and the Heavenly Father is restored.",

    { type: "quote", text: "For if, being enemies, we were reconciled to Elohim by the death of his Son, much more, being reconciled, we will be saved by his life. And not only, but also we glory in Elohim through our Lord Yehoshua Mashiah, by whom we have now obtained the reconciliation.", source: "Romans 5:10-11" },

    { type: "heading", text: "The True Blessing" },

    { type: "quote", text: "Mashiah has redeemed us away from the curse of the Torah, becoming a curse on our behalf, for it is written: Cursed, everyone that hangs on a wood \u2014 that the blessing of Abraham might come upon the nations in Mashiah Yehoshua, that we might receive the promise of the Spirit through faith.", source: "Galatians 3:13-14" },

    "In this passage, Paulos (Paul) declares that Yehoshua became a curse, so that the blessing of Abraham might come upon us, and that we ourselves might become a blessing. He was alluding to the mosaic Torah, detailed in Deuteronomy, chapter 21, verses 22 to 23. YHWH (the LORD) declared that all those who were hanged on a tree were a curse, because being hanged on a piece of wood in public view was proof that the condemned person was a curse. Likewise, by being nailed to the cross in full view of everyone, Yehoshua became a curse for us, in order to redeem us from the curse of the Torah, which rests upon all humans, whether they are Israelites or people from the nations.",

    { type: "quote", text: "but Elohim shows his love toward us, that, we being still sinners, Mashiah died for us.", source: "Romans 5:8" },

    { type: "quote", text: "He who truly did not spare his own Son, but delivered him up for us all, how will he not also graciously give us all things with him?", source: "Romans 8:32" },

    { type: "quote", text: "and walk in love, as Mashiah also has loved us, and has given himself for our sake as an offering and a sacrifice to Elohim for a sweet-smelling odor.", source: "Ephesians 5:2" },

    { type: "quote", text: "having given himself on behalf of our sins\u2026", source: "Galatians 1:4" },

    "In light of these passages, it is clear that the death of the Mashiah on the cross is a work accomplished perfectly. Indeed, it destroyed the curse that weighed upon our heads and restored us to the presence of the Father. Through it we can obtain the blessing, which is the salvation of our souls. As long as you remain obedient to the Word of the Lord, no curse can touch you, Hallelujah!",

    { type: "heading", text: "To carry one\u2019s cross" },

    { type: "quote", text: "And whoever does not carry his cross and come after me cannot be my disciple.", source: "Loukas 14:27" },

    "Having benefited from all the effects of the cross of Yehoshua Ha Mashiah, He leads us to follow Him while in turn carrying our own cross. By carrying our cross behind Yehoshua, we have the assurance of sharing in eternal life, which is the salvation of our souls. But it is clear that the cross that every disciple of the Lord must bear is not a physical pole or stake. Yehoshua does not ask us to make material crosses for ourselves, in order to wear them around our necks or on our shoulders. The cross we must bear represents first and foremost the sufferings of the Lord: \u201cTherefore Mashiah having suffered for us in the flesh, arm yourselves also with the same mind. For he having suffered in the flesh has been freed from sin\u201d (1 Petros 4:1).",

    { type: "heading", text: "The enemies of the cross" },

    "The Lord Yehoshua Ha Mashiah has made atonement for our sins, in order to bring us to Elohim. For the Mashiah is the propitiation for our sins, but He is also Himself the atoning sacrifice. With sin removed, sins confessed, forgiveness obtained, and the burnt offering given, the way is open for the joy of the Feast of Tabernacles. Indeed, the Feast of Tabernacles was the last feast of YHWH; it marked the end of the Jewish religious cycle. It was the celebration offered to Elohim who had provided shelter for his people during their journey through the desert, after the Exodus from Egypt. Today, Christians are the dwelling places (tabernacles or tents) of Elohim on Earth, for after being purified, their bodies house the Holy Spirit.",

    "Unfortunately, many reject this marvelous work that the Lord has won for us through his cross. They prefer to live according to the flesh and dedicate their lives to chasing after riches and vanities instead of following the Mashiah by carrying their cross daily. Others knowingly fight this work by introducing pernicious doctrines into the church, doctrines designed to lead Christians astray from the faith and keep them under the control of men possessed by unclean spirits.",

    { type: "heading", text: "4.1) The flesh and its desires" },

    { type: "quote", text: "And he said to them all: If anyone wants to come after me, let him deny himself, and take up his cross daily, and follow me. For whoever desires to save his soul will lose it, but whoever loses his soul for my sake will save it.", source: "Loukas 9:23-24" },

    "Here the Lord addresses those among the crowd and the disciples who want to follow Him to inherit eternal life. Yehoshua gives them the condition: to deny themselves and take up their cross; but He also provides an important clarification through which we understand that among those who want to follow Him, there are those who will actually lose their souls and be saved, and those who will want to save their souls and lose them. By this, the Lord reminds us that among those who call themselves Christians, there are those who are true and will inherit salvation, and there are those who will shipwreck their faith because they will prove incapable of paying the price demanded by Yehoshua. Thus, the true Christian is not content with simply wanting to deny themselves and take up their cross. He carries his cross and is led by the Holy Spirit. The work of the cross is perfectly accomplished in his life. Whereas he who wants to save his soul rejects the work of the cross in his life. For the mere desire to save one\u2019s soul is enough to disqualify one from salvation, because he is thus led by the flesh.",

    "The fact that the will of humankind is taken into account in the work of salvation demonstrates that all the powers that prevented humankind from serving Yehoshua have been completely overcome. Indeed, before the cross we could say, like Paulos (Paul): \u201cFor we know that the Torah is spiritual, but I am carnal, sold under sin. For what I accomplish, I do not understand it, for what I want, is what I do not practise it, but what I hate, is what I do. If then I do what I do not want, I confess that the Torah is good. But now it is no more I that do it, but sin dwelling in me. For I know that there is nothing good in me, that is, in my flesh, for to will is near me, but I find not the means to accomplish what is good. For the good that I want I do not do, but the evil that I do not want, that I practice. But if I do what I do not want, it is no longer I who do it, but sin dwelling in me. I find then this Torah within me: when I want to do what is good, evil is near me. For I delight in the Torah of Elohim according to the inner man. But I see another Torah in my members, warring against the Torah of my mind, and making me captive to the Torah of sin that is in my members. O wretched human being that I am! Who will deliver me out of the body of this death?\u201d But since the cross, we have become capable of serving Elohim according to his conditions.",

    "Many people prioritize their own will over that of the Lord. They refuse to renounce themselves in order to be able to serve Elohim according to His conditions, even though Yehoshua has conquered all the powers that prevented us from serving Him. This is why, since the cross, only human will is capable of rising up against divine will and leading us astray from the path of salvation. We are completely delivered. Yehoshua has won a total victory over the enemy. We cannot blame the flesh, demons, or the world to justify our disobedience. If we let go of our emotions, our will, our reasoning, our desires, our culture, our surroundings, etc. Our old human nature influences our will and prioritizes the Lord, and because of this we miss out on salvation, we have only ourselves to blame. Thus, wanting to save one\u2019s soul simply means rejecting the cross and therefore refusing to walk according to the conditions established by Elohim. For the cross every Christian must bear is also about humbling oneself, as Yehoshua did. It means renouncing everything that can lead us to glorify ourselves, in order to live as a servant. Consequently, humbling oneself daily to take the position of servant depends solely on the will of the individual. Yet, many among Christians seek elevation, positions of power, and honors. They may be persecuted by outsiders because of their adherence to the Christian faith, but within their churches and families, they demand a place of honor.",

    "In summary, those who live according to the Gospel of the cross walk against the current; they are persecuted, rejected, and decried as deceivers because of their faith, for the world does not accept the truth. Every day, we must carry our cross, that is, accept to walk in the truth of the Gospel despite the struggles. Stand firm in a world where sin is normalized and institutionalized.",

    "To bear one\u2019s cross is to live in sanctification and obedience to the Lord\u2019s commandments. It is also resistance to the devil and his tempting offers. To bear one\u2019s cross is to refuse to drink the wine of debauchery and to eat the food of kings, of Babylon. A person who bears their cross will live like Shadrach, Meshach, and Abednego, who refused to worship an idol so as not to disobey YHWH their Elohim, despite the sentence of King Nebuchadnezzar. Thus, those who wish to live godly and discreetly in the Mashiah are persecuted (2 Timothy 3:12).",

    "For in this generation where good is called evil, and evil is called good, in a world where injustice is becoming the norm, living according to piety has become risky, for the righteous are persecuted, called backward and medieval. Indeed, Yehoshua urges us to accumulate treasure in heaven, and not to become rich in order to lead a life of luxury on Earth. Yet, we live in a world where the wealthiest 1% own nearly half of the world\u2019s wealth and where the population is pressured to acquire more and more possessions and material wealth. A world that also teaches to flaunt this wealth, to display it with pride before everyone. Despite the beauty of the work accomplished by our Savior, the Gospel of the cross is rejected today and replaced by a gospel exalting money, human beings, material possessions, etc. Social needs are emphasized. Counseling, therapy, and many other techniques have replaced the cross. Truth has almost disappeared, and everything is being done to make it disappear completely. Thus, anti-biblical laws will be passed more and more frequently, and congregations that refuse to submit to them will be persecuted.",
  ],
  supportingVerses: [],
  closing: "",
  footnotes: {
    "Mattithyah": "Matthew",
    "Loukas": "Luke",
    "Yohanan": "John",
    "1 Petros": "1 Peter",
    "Paulos": "Paul"
  }
};
