/**
 * Booklet 1, Chapter 6: One Body
 * Author: Franck
 *
 * See EXAMPLE-CHAPTER.js for all available content block types.
 */
BOOKLET_CONTENT["1-6"] = {
  content: [
    { type: "quote", text: "I therefore, the prisoner of the Lord, beg you that you walk in a manner worthy of the vocation with which you were called, with all humility and gentleness, with patience, bearing one another in love, striving to keep the unity of the Spirit in the bond of peace: One body, and one Spirit, also as you were called in one hope of your calling. One Lord, one faith, one baptism, one Elohim (God) and Father of all, who is above all, and through all, and in you all.", source: "Ephesians 4:1-6" },

    "The disciple of Yehoshua (Jesus) should understand the notion of One Body. Without comprehending this notion, he/she might be an obstacle to the work Elohim is doing. \u201cNow you are the body of Mashiah (Christ), and members in particular\u201d (1 Corinthians 12:27). The Apostle Paulos (Paul) was writing the letter to the assembly of Elohim which is at Corinth, to them that are sanctified in Mashiah Yehoshua, and called saints (1 Corinthians 1:2). He further emphasized that the saint\u2019s persons who were part of the assembly of Elohim in Corinth are the Body of Mashiah. We understand more clearly why in Ephesians 5:23, the Testament of Yehoshua said \u201cfor the husband is the head of the wife, as also Mashiah is the head of the Assembly which is his body and of which he is the Savior.\u201d So, The Lord Yehoshua takes all believers (all persons who went through the process of repentance, and who are born from above) in the world and make them to constitute His Body. What a Privilege!",

    { type: "quote", text: "For as the body is one, and has many members, and all the members of the one body, being many, are one body, so also is Mashiah. For also in one Spirit were we all baptized into one body, whether Jews or Greek, whether slaves or free, and we have all been made to drink into one Spirit. For indeed the body is not one member, but many. If the foot was saying: Because I am not the hand, I am not out of the body? It is not, because of this, not out of the body! And if the ear was saying: Because I am not the eye, I am not out of the body? It is not, because of this, not out of the body! If the whole body were an eye, where were the hearing? If the whole were hearing, where were the smelling? But now has Elohim set the members each one of them in the body, as he would. And if all were one member, where were the body? But now, there are indeed many members, and one body. And the eye cannot say to the hand: I have no need of you. Nor again the head to the feet: I have no need of you. But much rather those members of the body, seeming to be weaker, are necessary. And those that we think to be less honourable of the body, upon these we put more abundant honour, and our unseemly parts have more abundant comeliness, but our honourable parts have no need. But Elohim has mixed the body together, having given more abundant honour to that part which lacked, that there should be no schism in the body, but that the members should care the same one for another. And whether one member suffer, all the members suffer with it; or one member is honoured, all the members rejoice with it.", source: "1 Corinthians 12:12-26" },

    "We have a good understanding of the Body in the above verses: One Body of Mashiah with many members. It is like a team. Let us take for example that there is food on a table. The eyes will monitor and the hand, that is a member of the body, must hold the spoon, take the food and feed the mouth. The mouth in its turn will play its part. The same for the teeth, the stomach etc\u2026 It is a whole system and mechanism. Let us say for an instance that the hand is striking and it does not want to play its part, or the teeth is striking and does not want to play its part. The stomach will not receive any food and at the end of the day the body will be tired and the same members that were striking will be affected by the hunger.",

    "Elohim set the members each one of them in the body, as he would. \u201cSo then, it is not of him willing, nor of him running, but on Elohim who shows mercy.\u201d (Romans 9:16). So it can be that in the body of Mashiah, a sister from Free State Province is the hand as a member, another brother from Gauteng Province is the foot, another father from Western Cape Province is the arm, another mother from Limpopo Province is the mouth, another boy from North West Province is the nose, another girl from Mpumalanga Province is the tongue, another brother from KwaZulu Natal is the back, another sister from Northern Cape Province is the eye, and another father from Eastern Cape Province is the neck. Many members, and one body so that The Complete Will of Our Elohim Yehoshua be done. Isn\u2019t it beautiful for the 9 persons listed above from the 9 Provinces of South Africa, coming together and being let by The Holy Spirit and accomplish a specific task entrusted to them by The Lord? \u201cFor we are his work, created in Mashiah Yehoshua on good works, which Elohim prepared beforehand that we should walk in them.\u201d Ephesians 2:10.",

    { type: "quote", text: "He that descended is the same also that ascended above all heavens, that he might fill all things. And he himself gave indeed the apostles, and the prophets, and the evangelists, and the shepherds and teachers, for the equipping of the saints, for the work of the service, for the building up of the body of Mashiah, till we all come in the unity of the faith, and of the precise and correct knowledge of the Son of Elohim, to a perfect man, to the measure of the stature of the fulness of Mashiah.", source: "Ephesians 4:10-13" },

    "The Lord gave\u2026So there shouldn\u2019t be any jealousies, or envies. As same way the hand can\u2019t envy the mouth, let us not envy one another.",

    { type: "quote", text: "For as we have many members in one body, and all members do not have the same function, so we, who are many, are one body in Mashiah, but each individually members of one another. But, having different gifts of grace according to the grace that has been given to us: whether prophecy, according to the proportion of faith, whether service, in the service. Either he who teaches, in teaching, or he exhorting, in the exhortation; he imparting, in simplicity, he leading, with zeal, he exercising mercy, with joy.", source: "Romans 12:4-8" },

    "All members do not have the same function. Let us use the different gifts, Yehoshua gave to us to serve the other members of His Body for His Glory.",

    { type: "quote", text: "As there is one bread, we, who are many, are one body, for we all partake of the one bread.", source: "1 Corinthians 10:17" },
  ],
  supportingVerses: [],
  closing: ""
};
